### PR TITLE
fix: flaky tests

### LINKED ISSUE #369: Fix flakey CI tests
Some tests are randomly coming up as failures in our CI workflows, we should investigate these tests further and remove the flakiness

### PR DESCRIPTION
**Pull request by rwalworth**
**Description**:
There were a few flaky tests showing up in CI, this PR fixes the flakiness on those.

**Related issue(s)**:

Fixes #369 

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

### CODE REVIEW

File: src/tests/crypto-service/test-account-update-transaction.ts [hunk 1]
```diff
@@ -625,8 +625,9 @@ describe("AccountUpdateTransaction", function () {
 
     it("(#4) Updates the expiration time of an account to 8,000,002 seconds from the current time", async function () {
       try {
-        const expirationTime = (
-          Math.floor(Date.now() / 1000) + 8000002
+        // Use Math.ceil to prevent flakiness.
+        const expirationTime = Math.ceil(
```
Comment (ivaylogarnev-limechain) [inline src/tests/crypto-service/test-account-update-transaction.ts:629]: Isn't `Math.ceil()` rebundant?

Comment (rwalworth) [reply src/tests/crypto-service/test-account-update-transaction.ts]: Yep, fixed

**Review by ivaylogarnev-limechain — APPROVED** [review]
LGTM
